# -*- coding: utf-8 -*-
"""Kết luận."""

BLOCKS = [
    ("h1", "KẾT LUẬN", "KẾT LUẬN"),
    ("p", "Cặp phạm trù bản chất và hiện tượng phản ánh mối quan hệ giữa mặt bên trong, tất nhiên, tương đối "
          "ổn định và mặt bên ngoài, biến đổi, có thể quan sát trực tiếp của sự vật. Lịch sử triết học cho "
          "thấy quan hệ này đã được giải quyết theo những lập trường khác nhau, từ sự phân biệt trực quan của "
          "triết học cổ đại, qua sự tách rời “hiện tượng” và “vật tự nó” của Cantơ, đến biện chứng duy tâm của "
          "Hêghen. Chủ nghĩa duy vật biện chứng khẳng định bản chất và hiện tượng đều tồn tại khách quan, "
          "thống nhất và đối lập với nhau; hiện tượng có thể biểu hiện bản chất dưới dạng xuyên tạc, tức là "
          "giả tượng; bản chất có nhiều cấp độ; và ranh giới giữa bản chất và hiện tượng là ranh giới lịch sử "
          "giữa cái đã biết và cái chưa biết, được dịch chuyển bằng thực tiễn. Từ đó, phép biện chứng duy vật "
          "đặt ra yêu cầu nhận thức phải xuất phát từ hiện tượng, phân biệt hiện tượng với giả tượng, không "
          "dừng lại ở hiện tượng mà không ngừng đi vào những cấp độ bản chất sâu hơn, và lấy thực tiễn làm "
          "tiêu chuẩn kiểm nghiệm. Cặp phạm trù này có mối liên hệ chặt chẽ với các cặp phạm trù khác và với "
          "ba quy luật cơ bản của phép biện chứng, nên chỉ có thể được vận dụng đúng khi được đặt trong toàn "
          "bộ hệ thống của phép biện chứng duy vật."),
    ("p", "Phân tích năm trường hợp của lịch sử hóa học (sự cháy, tính tuần hoàn của các nguyên tố, các thuyết "
          "acid – base, đồng phân và tính bất đối, động học enzyme) cho thấy nhận thức hóa học đã vận động phù "
          "hợp với con đường mà phép biện chứng duy vật khái quát: từ hiện tượng đến bản chất, từ bản chất cấp "
          "thấp đến bản chất cấp cao; giả tượng được vượt qua bằng việc kiểm soát điều kiện biểu hiện; mâu "
          "thuẫn giữa lý thuyết và dữ kiện là động lực phát triển; và các lý thuyết sau phủ định các lý thuyết "
          "trước theo lối phủ định biện chứng, có kế thừa. Trường hợp thalidomide cho thấy việc dừng lại ở một "
          "cấp độ bản chất chưa đầy đủ có thể dẫn đến những hậu quả thực tiễn nghiêm trọng."),
    ("p", "Vận dụng vào đánh giá hoạt tính ức chế enzyme của hợp chất thiên nhiên, tiểu luận đã chỉ ra rằng "
          "giá trị IC_{50} và điểm số docking thuộc về hiện tượng, trong khi bản chất cần nhận thức là tương "
          "tác đặc hiệu giữa phân tử và đích sinh học cùng khả năng tương tác đó diễn ra trong cơ thể. Các "
          "dạng giả tượng phổ biến gồm ức chế do kết tập keo, hợp chất gây nhiễu đa phép thử, sự không tương "
          "đồng giữa enzyme mô hình và đích sinh học, tạp chất, và việc tuyệt đối hóa kết quả mô phỏng. Tỷ lệ "
          "tái lập thấp của dữ liệu tiền lâm sàng là biểu hiện ở quy mô lớn của việc đồng nhất hiện tượng với "
          "bản chất. Nguyên nhân chủ quan của các sai lệch này là phương pháp tư duy siêu hình; xét theo quan "
          "hệ giữa lý luận và thực tiễn, nó biểu hiện dưới hai dạng đối lập là bệnh kinh nghiệm và bệnh giáo "
          "điều; bên cạnh đó là những điều kiện xã hội của hoạt động nghiên cứu."),
    ("p", "Trên cơ sở đó, tiểu luận đề xuất bốn nguyên tắc: xuất phát từ hiện tượng được ghi nhận đầy đủ và "
          "có kiểm soát; phân biệt hiện tượng với giả tượng bằng các thí nghiệm trực giao; đi từ bản chất cấp "
          "một đến bản chất sâu hơn thông qua động học enzyme, đo liên kết trực tiếp và quan hệ cấu trúc – "
          "hoạt tính; xem xét hiện tượng trong điều kiện lịch sử – cụ thể và lấy thực tiễn làm tiêu chuẩn. "
          "Các nguyên tắc này là sự cụ thể hóa của các nguyên tắc phương pháp luận chung của phép biện chứng "
          "duy vật và được thể hiện thành quy trình sáu cấp độ, với yêu cầu cốt lõi là mức độ khẳng định "
          "trong kết luận phải tương xứng với cấp độ bằng chứng đạt được. Việc vận dụng cũng đòi hỏi tránh "
          "hai khuynh hướng cực đoan: chấp nhận mọi kết quả dương tính như biểu hiện trực tiếp của bản chất, "
          "và loại bỏ máy móc các hợp chất chỉ dựa trên dấu hiệu cấu trúc bên ngoài."),
    ("p", "Những kết quả chính của tiểu luận có thể được tóm tắt ở ba phương diện. *Về lý luận*, tiểu luận "
          "đã làm rõ ba luận điểm có ý nghĩa đối với nhận thức trong khoa học thực nghiệm: ranh giới giữa bản "
          "chất và hiện tượng là ranh giới lịch sử, được dịch chuyển bằng thực tiễn và bằng sự phát triển của "
          "phương tiện nhận thức; kết quả đo là hiện tượng của một quan hệ giữa đối tượng, phương tiện đo và "
          "điều kiện đo, chứ không đơn thuần là thuộc tính của đối tượng; giả tượng chỉ có thể được vượt qua "
          "bằng việc làm rõ và thay đổi những điều kiện đã sinh ra nó. *Về phương pháp*, tiểu luận đã vận "
          "dụng nguyên tắc thống nhất giữa lôgíc và lịch sử để đối chiếu con đường nhận thức của lịch sử hóa "
          "học với con đường nhận thức trong một công trình nghiên cứu cụ thể, và đã chuyển các yêu cầu "
          "phương pháp luận chung thành những nguyên tắc có thể kiểm tra được bằng thực nghiệm. *Về thực "
          "tiễn*, quy trình sáu cấp độ, tình huống minh họa và các kiến nghị có thể được sử dụng trực tiếp "
          "trong thiết kế thí nghiệm, trình bày kết quả và phản biện công bố trong lĩnh vực hóa học hợp chất "
          "thiên nhiên."),
    ("p", "Kết quả của tiểu luận khẳng định vai trò phương pháp luận của triết học Mác – Lênin đối với khoa "
          "học tự nhiên: triết học không cung cấp các phép thử cụ thể, nhưng cung cấp cơ sở để hiểu vì sao "
          "các phép thử ấy là cần thiết, để kết hợp chúng thành một hệ thống, và để phát biểu kết luận ở "
          "đúng mức độ mà bằng chứng cho phép. Mối quan hệ giữa triết học và khoa học tự nhiên được thể "
          "hiện ở đây theo cả hai chiều: các dữ kiện của lịch sử hóa học và của nghiên cứu hóa dược hiện đại "
          "làm phong phú thêm nội dung của cặp phạm trù bản chất và hiện tượng, còn cặp phạm trù này cung cấp "
          "một khung phương pháp luận thống nhất để lý giải và sắp xếp các biện pháp kỹ thuật vốn được đề xuất "
          "riêng lẻ. Đối với bản thân học viên, tiểu luận có ý nghĩa định hướng "
          "trực tiếp cho việc thiết kế thí nghiệm trong nghiên cứu hóa học hợp chất thiên nhiên: không dừng "
          "lại ở việc báo cáo một giá trị IC_{50}, mà xây dựng hệ thống bằng chứng nhiều cấp độ, kết hợp phân "
          "lập với bán tổng hợp dẫn xuất để khảo sát quan hệ cấu trúc – hoạt tính, và kiểm chứng trên mô hình "
          "phù hợp với đích sinh học."),
    ("p", "Tiểu luận còn một số giới hạn. Phạm vi phân tích mới dừng ở các phép thử ức chế enzyme *in vitro*; "
          "các trường hợp lịch sử hóa học được chọn nhằm minh họa, chưa bao quát toàn bộ lịch sử của ngành; "
          "thực trạng công bố trong nước chưa được khảo sát định lượng. Việc mở rộng phân tích sang các phép "
          "thử trên tế bào, vận dụng sâu hơn các cặp phạm trù khác như nguyên nhân và kết quả, khả năng và "
          "hiện thực, và khảo sát có hệ thống các công bố về hoạt tính sinh học của hợp chất thiên nhiên ở "
          "Việt Nam là những hướng có thể tiếp tục. Ngoài ra, các nguyên tắc và quy trình được đề xuất cần "
          "được kiểm nghiệm thêm qua thực tiễn áp dụng trong các nhóm nghiên cứu, đúng với luận điểm thực tiễn "
          "là tiêu chuẩn của chân lý; bản thân quy trình này cũng là một tri thức tương đối, cần được bổ sung "
          "và điều chỉnh cùng với sự phát triển của nhận thức khoa học."),
]
